version: '2'


services:
  nginx:
    image: nginx:1.14
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
    command: /bin/bash -c "nginx -g 'daemon off;'"
    links:
     - uwsgi_daemon

  uwsgi_daemon:
    build:
      context: .
      dockerfile: ./build-daemon.dockerfile
    volumes:
     - .:/home/ip2w
    privileged: true